### ISSUE TITLE
SASS and SCSS Modules

### ISSUE THREAD

**Issue by MayhemBlizSP** [davshoward/gatsby-starter-honey#1]
Hi Davs, Love the Gatsby starter! Will you be introducing SASS and SCSS Modules or just sticking with CSS for now?

**Comment by davshoward** [comment]
Thanks :-)

No intention to no, want to try to keep it lightweight/baseline. If you want to add SASS though you'd likely just need to install 'node-sass gatsby-plugin-sass' and add 'gatsby-plugin-sass' to the gatsby-config.
